version: '3'
services:
  postgresql:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: housing
    volumes:
      - ./data:/var/lib/postgresql/data