"""empty message

Revision ID: b877e4fb0240
Revises: 0aa0eeaf6c38
Create Date: 2023-12-19 22:17:25.484050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = 'b877e4fb0240'
down_revision: Union[str, None] = '0aa0eeaf6c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home', 'location',
               existing_type=sa.VARCHAR(),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True,
               postgresql_using='location::geometry')
    op.drop_index('ix_home_location', table_name='home')
    op.create_index('idx_home_location', 'home', ['location'], unique=False, postgresql_using='gist')
    op.drop_constraint('room_home_fkey', 'room', type_='foreignkey')
    op.create_foreign_key(None, 'room', 'home', ['home'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key('room_home_fkey', 'room', 'home', ['home'], ['id'])
    op.drop_index('idx_home_location', table_name='home', postgresql_using='gist')
    op.create_index('ix_home_location', 'home', ['location'], unique=False)
    op.alter_column('home', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
