"""empty message

Revision ID: 2348648b2e99
Revises: d83ddb2d701a
Create Date: 2023-12-13 18:55:18.893655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = '2348648b2e99'
down_revision: Union[str, None] = 'd83ddb2d701a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home', 'location',
               existing_type=sa.VARCHAR(),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.drop_index('ix_home_location', table_name='home')
    op.create_index('idx_home_location', 'home', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_home_location', table_name='home', postgresql_using='gist')
    op.create_index('ix_home_location', 'home', ['location'], unique=False)
    op.alter_column('home', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
