"""empty message

Revision ID: 7e22734ec77d
Revises: ce06cf2d680b
Create Date: 2023-12-13 16:40:05.000197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e22734ec77d'
down_revision: Union[str, None] = 'ce06cf2d680b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'sensor',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_room_name', table_name='room')
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_index(op.f('ix_room_sensor'), 'room', ['sensor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_sensor'), table_name='room')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.create_index('ix_room_name', 'room', ['name'], unique=False)
    op.alter_column('room', 'sensor',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
