"""empty message

Revision ID: 0a8d7ebd8f0e
Revises: 7391cce2d049
Create Date: 2023-12-09 13:31:19.346455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8d7ebd8f0e'
down_revision: Union[str, None] = '7391cce2d049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('location', sa.String(), nullable=True))
    op.create_index(op.f('ix_home_location'), 'home', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_location'), table_name='home')
    op.drop_column('home', 'location')
    # ### end Alembic commands ###
