"""empty message

Revision ID: d173db771357
Revises: 85066e6c35da
Create Date: 2023-12-12 15:43:36.239002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd173db771357'
down_revision: Union[str, None] = '85066e6c35da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_home_description', table_name='home')
    op.create_index(op.f('ix_home_description'), 'home', ['description'], unique=False)
    op.drop_index('ix_home_location', table_name='home')
    op.create_index(op.f('ix_home_location'), 'home', ['location'], unique=False)
    op.drop_index('ix_home_name', table_name='home')
    op.create_index(op.f('ix_home_name'), 'home', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_name'), table_name='home')
    op.create_index('ix_home_name', 'home', ['name'], unique=False)
    op.drop_index(op.f('ix_home_location'), table_name='home')
    op.create_index('ix_home_location', 'home', ['location'], unique=False)
    op.drop_index(op.f('ix_home_description'), table_name='home')
    op.create_index('ix_home_description', 'home', ['description'], unique=False)
    # ### end Alembic commands ###
