"""empty message

Revision ID: ba58b6ade5f4
Revises: d8ddb88d3243
Create Date: 2023-11-30 13:05:30.136185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ba58b6ade5f4'
down_revision: Union[str, None] = 'd8ddb88d3243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_address'), 'home', ['address'], unique=True)
    op.create_index(op.f('ix_home_description'), 'home', ['description'], unique=True)
    op.create_index(op.f('ix_home_id'), 'home', ['id'], unique=False)
    op.create_index(op.f('ix_home_name'), 'home', ['name'], unique=True)
    op.create_table('home_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home'], ['home.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_user_id'), 'home_user', ['id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('sensor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home'], ['home.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_home_user_id'), table_name='home_user')
    op.drop_table('home_user')
    op.drop_index(op.f('ix_home_name'), table_name='home')
    op.drop_index(op.f('ix_home_id'), table_name='home')
    op.drop_index(op.f('ix_home_description'), table_name='home')
    op.drop_index(op.f('ix_home_address'), table_name='home')
    op.drop_table('home')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
